services:
    frontend:
        build:
            context: "./client"
        ports:
            - "4173:4173"
        environment:
            SERVER_URL: "http://backend:8080"

    backend:
        build:
            context: "./server"
        ports:
            - "8080:8080"
        environment:
            POSTGRES_HOST: "postgres"
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy

    postgres:
        image: postgres:17-alpine
        container_name: picourl-postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U cashflow-admin -d cashflow"]
            interval: 5s
            timeout: 5s
            retries: 3

    redis:
        image: redis:8.2.3-alpine
        container_name: picourl-redis
        restart: always
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
        volumes:
            - redis-data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
            interval: 5s
            timeout: 5s
            retries: 3

volumes:
    postgres_data:
    redis-data:
